### Data Encoding

#### 1.Nominal/One-Hot Encoding:

One hot encoding also known as nominal encoding is a technique used to represent categorical data as numerical data which is needed for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
#sample dataframe for demonstration

color_df = pd.DataFrame(
    {"color": ['red', 'blue', 'yellow', 'blue', 'blue', 'red', 'yellow']}
)
color_df

    color
0     red
1    blue
2  yellow
3    blue
4    blue
5     red
6  yellow

In [3]:
ohe_obj = OneHotEncoder()
color_data=ohe_obj.fit_transform(color_df[['color']]).toarray()

In [4]:
cols=ohe_obj.get_feature_names_out()

In [5]:
new_df = pd.DataFrame(data=color_data, columns=cols)
new_df

   color_blue  color_red  color_yellow
0         0.0        1.0           0.0
1         1.0        0.0           0.0
2         0.0        0.0           1.0
3         1.0        0.0           0.0
4         1.0        0.0           0.0
5         0.0        1.0           0.0
6         0.0        0.0           1.0

In [6]:
#to encode new data

ohe_obj.transform([['blue']]).toarray()

d:\Machine_Learning_Works\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

#### Using tips dataset

In [7]:
import seaborn as sns
tips_df = sns.load_dataset('tips')

In [8]:
tips_df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
tips_df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [10]:
#applying encoding on smoker feature

encoder = OneHotEncoder()
smoker_data = encoder.fit_transform(tips_df[['smoker']]).toarray()

full_tips_df = pd.concat([tips_df, pd.DataFrame(data=smoker_data, columns=encoder.get_feature_names_out())], axis=1)
full_tips_df

,total_bill,tip,sex,smoker,day,time,size,smoker_No,smoker_Yes
0,16.99,1.01,Female,No,Sun,Dinner,2,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,1.0,0.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,1.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0.0,1.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0
242,17.82,1.75,Male,No,Sat,Dinner,2,1.0,0.0
243,18.78,3.00,Female,No,Thur,Dinner,2,1.0,0.0

#### 2.Label Encoding:

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories.

In [11]:
color_df

    color
0     red
1    blue
2  yellow
3    blue
4    blue
5     red
6  yellow

In [12]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_encoder.fit_transform(color_df)

d:\Machine_Learning_Works\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([1, 0, 2, 0, 0, 1, 2])

In [13]:
#applying encoding on new data

label_encoder.transform(['blue'])

array([0])

#### 3.Ordinal Encoding:

It is used to encode categorical features that has intrinsic order or ranking. In this technique, each category is assigned a numerical value based on it's position in the order.

In [14]:
color_df

    color
0     red
1    blue
2  yellow
3    blue
4    blue
5     red
6  yellow

In [15]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder(categories=[['yellow', 'blue', 'red']])
ordinal_encoder.fit_transform(color_df[['color']])

array([[2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.]])

In [16]:
#to encode new data

ordinal_encoder.transform([['blue']])

d:\Machine_Learning_Works\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

### 4.Target Guided Ordinal Encoder

* It is a technique used to encode categorical variables based on their relationship with the target variables. This encoding technique is useful when we have a categorical variable with large number of unique categories, and we want to use this variable as a feature in our model.

* In this technique we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category.

In [24]:
df = pd.DataFrame(
    {"country": ["China", "India", "Japan", "Japan", "India", "China", "India"], 
     "target":[6, 9, 9, 7, 9, 9, 9 ]}
)

df

  country  target
0   China       6
1   India       9
2   Japan       9
3   Japan       7
4   India       9
5   China       9
6   India       9

In [30]:
country_dict=df.groupby('country')['target'].mean().to_dict()
country_dict

{'China': 7.5, 'India': 9.0, 'Japan': 8.0}

In [28]:
df['country_encoded'] = df['country'].map(country_dict)
df['country_encoded']

0    7.5
1    9.0
2    8.0
3    8.0
4    9.0
5    7.5
6    9.0
Name: country_encoded, dtype: float64

In [29]:
df

  country  target  country_encoded
0   China       6              7.5
1   India       9              9.0
2   Japan       9              8.0
3   Japan       7              8.0
4   India       9              9.0
5   China       9              7.5
6   India       9              9.0