### Data Encoding

#### 1.Nominal/One-Hot Encoding:

One hot encoding also known as nominal encoding is a technique used to represent categorical data as numerical data which is needed for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
#sample dataframe for demonstration

color_df = pd.DataFrame(
    {"color": ['red', 'blue', 'yellow', 'blue', 'blue', 'red', 'yellow']}
)
color_df

    color
0     red
1    blue
2  yellow
3    blue
4    blue
5     red
6  yellow

In [11]:
ohe_obj = OneHotEncoder()
color_data=ohe_obj.fit_transform(color_df[['color']]).toarray()

In [12]:
cols=ohe_obj.get_feature_names_out()

In [14]:
new_df = pd.DataFrame(data=color_data, columns=cols)
new_df

   color_blue  color_red  color_yellow
0         0.0        1.0           0.0
1         1.0        0.0           0.0
2         0.0        0.0           1.0
3         1.0        0.0           0.0
4         1.0        0.0           0.0
5         0.0        1.0           0.0
6         0.0        0.0           1.0

In [16]:
#to encode new data

ohe_obj.transform([['blue']]).toarray()

d:\Machine_Learning_Works\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])