### Student Performance Indicator - Model Training

In [14]:
#importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import RandomizedSearchCV

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [4]:
#importing dataset as dataframe

df = pd.read_csv("stud.csv")
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [5]:
#preparing independent and dependent variables

x = df.drop('math_score', axis=1)
y = df['math_score']

In [6]:
#getting categorical and numerical features

num_columns = [col for col in x.columns if x[col].dtype != "str"]
cat_columns = [col for col in x.columns if x[col].dtype == "str"]

In [15]:
#splitting data into train, test sets

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [13]:
#preprocessing data

one_hot_obj = OneHotEncoder(drop="first")
scaler_obj = StandardScaler()

preprocessor = ColumnTransformer([
    ("one_hot_encoding", one_hot_obj, cat_columns),
    ("standard_scaler", scaler_obj, num_columns)
], remainder="passthrough")

In [16]:
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [ ]:
#evalution function

def evaluation_results(y_test, y_pred):
    r2_value = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    return (r2_value, mse, mae)

In [31]:
models = {"Linear Regression": LinearRegression(),
          "Ridge": Ridge(),
          "Lasso": Lasso(),
          "Support Vector Regressor": SVR(),
          "KNN": KNeighborsRegressor(),
          "Decision Tree": DecisionTreeRegressor(),
          "Random Forest": RandomForestRegressor(),
          "Adaptive Boosting": AdaBoostRegressor(),
          "Cat Boosting": CatBoostRegressor(),
          "XG Boosting": XGBRegressor()}

train_performance_metrics = []
test_performance_metrics = []

for item in range(len(models.keys())):
    model_objs = list(models.values())
    model = model_objs[item]

    #model training
    model.fit(x_train, y_train)

    #model prediction 
    y_pred_train = model.predict(x_train)
    y_pred_test = model.predict(x_test)

    #performance metrics evalution
    train_performance_metrics.append(evaluation_results(y_train, y_pred_train))
    test_performance_metrics.append(evaluation_results(y_test, y_pred_test))

met_train=pd.DataFrame(data=train_performance_metrics, columns=['Train R_Square', 'Train MSE', 'Train MAE'], index=models.keys())
met_test=pd.DataFrame(data=test_performance_metrics, columns=['Test R_Square', 'Test MSE', 'Test MAE'], index=models.keys())
met = pd.concat([met_train, met_test], axis=1)
met

Learning rate set to 0.039525
0:	learn: 14.6182162	total: 759us	remaining: 759ms
1:	learn: 14.2679232	total: 1.16ms	remaining: 580ms
2:	learn: 13.9259502	total: 1.67ms	remaining: 557ms
3:	learn: 13.5925455	total: 2.19ms	remaining: 546ms
4:	learn: 13.2881685	total: 2.65ms	remaining: 528ms
5:	learn: 12.9738597	total: 3.2ms	remaining: 530ms
6:	learn: 12.6794798	total: 3.65ms	remaining: 517ms
7:	learn: 12.3815862	total: 4.07ms	remaining: 505ms
8:	learn: 12.0744423	total: 4.49ms	remaining: 495ms
9:	learn: 11.7821385	total: 5.02ms	remaining: 497ms
10:	learn: 11.5327154	total: 5.46ms	remaining: 491ms
11:	learn: 11.2696189	total: 5.87ms	remaining: 483ms
12:	learn: 11.0112102	total: 6.29ms	remaining: 478ms
13:	learn: 10.7949384	total: 6.73ms	remaining: 474ms
14:	learn: 10.5691504	total: 7.69ms	remaining: 505ms
15:	learn: 10.3395526	total: 8.19ms	remaining: 504ms
16:	learn: 10.1180379	total: 8.71ms	remaining: 504ms
17:	learn: 9.9323393	total: 9.16ms	remaining: 500ms
18:	learn: 9.7528727	total: 9.6ms	remaining: 496ms
19:	learn: 9.5518289	total: 10.1ms	remaining: 493ms
20:	learn: 9.3783846	total: 10.5ms	remaining: 489ms
21:	learn: 9.2011008	total: 10.9ms	remaining: 485ms
22:	learn: 9.0410879	total: 11.3ms	remaining: 481ms
23:	learn: 8.8689312	total: 11.7ms	remaining: 478ms
24:	learn: 8.7218734	total: 12.2ms	remaining: 477ms
25:	learn: 8.5726332	total: 12.7ms	remaining: 475ms
26:	learn: 8.4375798	total: 13.1ms	remaining: 474ms
27:	learn: 8.3040810	total: 13.6ms	remaining: 472ms
28:	learn: 8.1769954	total: 14ms	remaining: 470ms
29:	learn: 8.0605725	total: 14.4ms	remaining: 465ms
30:	learn: 7.9257040	total: 14.8ms	remaining: 463ms
31:	learn: 7.8144909	total: 15.2ms	remaining: 461ms
32:	learn: 7.6962727	total: 15.7ms	remaining: 459ms
33:	learn: 7.6052864	total: 16.1ms	remaining: 457ms
34:	learn: 7.5085080	total: 16.5ms	remaining: 456ms
35:	learn: 7.4182575	total: 17ms	remaining: 454ms
36:	learn: 7.3212694	total: 17.5ms	remaining: 455ms
37:	learn: 7.2296234	total: 17.8ms	remaining: 452ms
38:	learn: 7.1495156	total: 18.3ms	remaining: 450ms
39:	learn: 7.0695176	total: 18.8ms	remaining: 450ms
40:	learn: 6.9852878	total: 19.2ms	remaining: 449ms
41:	learn: 6.9201826	total: 19.7ms	remaining: 450ms
42:	learn: 6.8533237	total: 20.3ms	remaining: 451ms
43:	learn: 6.7875885	total: 20.7ms	remaining: 449ms
44:	learn: 6.7164041	total: 21.1ms	remaining: 448ms
45:	learn: 6.6479343	total: 21.5ms	remaining: 447ms
46:	learn: 6.5915937	total: 22ms	remaining: 445ms
47:	learn: 6.5359600	total: 22.4ms	remaining: 444ms
48:	learn: 6.4768355	total: 22.9ms	remaining: 444ms
49:	learn: 6.4225260	total: 23.3ms	remaining: 443ms
50:	learn: 6.3785059	total: 23.8ms	remaining: 443ms
51:	learn: 6.3272649	total: 24.3ms	remaining: 443ms
52:	learn: 6.2868265	total: 24.7ms	remaining: 442ms
53:	learn: 6.2407503	total: 25.2ms	remaining: 441ms
54:	learn: 6.1947417	total: 25.6ms	remaining: 439ms
55:	learn: 6.1458876	total: 26ms	remaining: 438ms
56:	learn: 6.1122068	total: 26.4ms	remaining: 437ms
57:	learn: 6.0758978	total: 26.8ms	remaining: 436ms
58:	learn: 6.0359936	total: 27.2ms	remaining: 434ms
59:	learn: 6.0016432	total: 27.7ms	remaining: 433ms
60:	learn: 5.9700060	total: 28.1ms	remaining: 433ms
61:	learn: 5.9321618	total: 28.6ms	remaining: 432ms
62:	learn: 5.8971602	total: 29ms	remaining: 432ms
63:	learn: 5.8681604	total: 29.5ms	remaining: 431ms
64:	learn: 5.8393693	total: 29.9ms	remaining: 430ms
65:	learn: 5.8157464	total: 30.3ms	remaining: 429ms
66:	learn: 5.7866709	total: 30.7ms	remaining: 427ms
67:	learn: 5.7597491	total: 31.1ms	remaining: 426ms
68:	learn: 5.7436008	total: 31.4ms	remaining: 423ms
69:	learn: 5.7224517	total: 31.8ms	remaining: 422ms
70:	learn: 5.7014308	total: 32.2ms	remaining: 421ms
71:	learn: 5.6777977	total: 32.6ms	remaining: 420ms
72:	learn: 5.6571174	total: 33ms	remaining: 419ms
73:	learn: 5.6378778	total: 33.5ms	remaining: 419ms
74:	learn: 5.6287252	total: 33.7ms	remaining: 416ms
75:	learn: 5.6064426	total: 34.2ms	remaining: 415ms
76:	learn: 5.5872152	total: 34.6ms	remaining: 415ms
77:	learn: 5.5689407	total: 35ms	remaining: 414ms
78:	learn: 5.5496075	total: 35.4ms	remaining: 413ms
79:	learn: 5.5355558	total: 35.8ms	remaining: 412ms
80:	learn: 5.5184279	total: 36.2ms	remaining: 411ms
81:	learn: 5.5009410	total: 36.6ms	remaining: 410ms
82:	learn: 5.4859533	total: 37ms	remaining: 409ms
83:	learn: 5.4688679	total: 37.4ms	remaining: 408ms
84:	learn: 5.4563242	total: 37.8ms	remaining: 407ms
85:	learn: 5.4439162	total: 38.2ms	remaining: 406ms
86:	learn: 5.4299227	total: 38.8ms	remaining: 407ms
87:	learn: 5.4145218	total: 39.2ms	remaining: 407ms
88:	learn: 5.3986366	total: 39.6ms	remaining: 406ms
89:	learn: 5.3855942	total: 40ms	remaining: 405ms
90:	learn: 5.3757325	total: 40.4ms	remaining: 404ms
91:	learn: 5.3626672	total: 40.8ms	remaining: 403ms
92:	learn: 5.3533765	total: 41.2ms	remaining: 402ms
93:	learn: 5.3404174	total: 41.6ms	remaining: 401ms
94:	learn: 5.3269045	total: 42ms	remaining: 400ms
95:	learn: 5.3143533	total: 42.4ms	remaining: 399ms
96:	learn: 5.3030904	total: 42.8ms	remaining: 398ms
97:	learn: 5.2948149	total: 43.2ms	remaining: 398ms
98:	learn: 5.2863640	total: 43.7ms	remaining: 398ms
99:	learn: 5.2724373	total: 44.2ms	remaining: 398ms
100:	learn: 5.2633716	total: 44.6ms	remaining: 397ms
101:	learn: 5.2565774	total: 45ms	remaining: 396ms
102:	learn: 5.2516848	total: 45.3ms	remaining: 395ms
103:	learn: 5.2455386	total: 45.7ms	remaining: 394ms
104:	learn: 5.2367170	total: 46.1ms	remaining: 393ms
105:	learn: 5.2315415	total: 46.4ms	remaining: 391ms
106:	learn: 5.2220897	total: 46.8ms	remaining: 390ms
107:	learn: 5.2148845	total: 47.2ms	remaining: 390ms
108:	learn: 5.2077015	total: 47.6ms	remaining: 389ms
109:	learn: 5.2032898	total: 47.8ms	remaining: 387ms
110:	learn: 5.1978820	total: 48.2ms	remaining: 386ms
111:	learn: 5.1926255	total: 48.6ms	remaining: 386ms
112:	learn: 5.1868724	total: 49.1ms	remaining: 385ms
113:	learn: 5.1796712	total: 49.5ms	remaining: 385ms
114:	learn: 5.1731891	total: 49.9ms	remaining: 384ms
115:	learn: 5.1661811	total: 50.3ms	remaining: 383ms
116:	learn: 5.1616673	total: 50.7ms	remaining: 383ms
117:	learn: 5.1558514	total: 51.1ms	remaining: 382ms
118:	learn: 5.1508619	total: 51.5ms	remaining: 381ms
119:	learn: 5.1451642	total: 51.9ms	remaining: 381ms
120:	learn: 5.1434562	total: 52.2ms	remaining: 379ms
121:	learn: 5.1378275	total: 52.6ms	remaining: 378ms
122:	learn: 5.1313988	total: 53ms	remaining: 378ms
123:	learn: 5.1276464	total: 53.3ms	remaining: 377ms
124:	learn: 5.1210438	total: 53.7ms	remaining: 376ms
125:	learn: 5.1130592	total: 54.3ms	remaining: 377ms
126:	learn: 5.1096461	total: 54.8ms	remaining: 376ms
127:	learn: 5.1037944	total: 55.2ms	remaining: 376ms
128:	learn: 5.0999366	total: 55.6ms	remaining: 375ms
129:	learn: 5.0932810	total: 56ms	remaining: 375ms
130:	learn: 5.0877620	total: 56.4ms	remaining: 374ms
131:	learn: 5.0841979	total: 56.7ms	remaining: 373ms
132:	learn: 5.0797745	total: 57.1ms	remaining: 372ms
133:	learn: 5.0753160	total: 57.5ms	remaining: 372ms
134:	learn: 5.0721544	total: 57.9ms	remaining: 371ms
135:	learn: 5.0662783	total: 58.3ms	remaining: 370ms
136:	learn: 5.0602447	total: 58.7ms	remaining: 370ms
137:	learn: 5.0525591	total: 59.1ms	remaining: 369ms
138:	learn: 5.0487155	total: 59.5ms	remaining: 369ms
139:	learn: 5.0444911	total: 60ms	remaining: 369ms
140:	learn: 5.0386450	total: 60.4ms	remaining: 368ms
141:	learn: 5.0318092	total: 60.9ms	remaining: 368ms
142:	learn: 5.0260739	total: 61.3ms	remaining: 367ms
143:	learn: 5.0227617	total: 61.7ms	remaining: 367ms
144:	learn: 5.0192103	total: 62.1ms	remaining: 366ms
145:	learn: 5.0157586	total: 62.5ms	remaining: 365ms
146:	learn: 5.0123718	total: 62.9ms	remaining: 365ms
147:	learn: 5.0051627	total: 63.3ms	remaining: 364ms
148:	learn: 4.9985699	total: 63.7ms	remaining: 364ms
149:	learn: 4.9947381	total: 64.1ms	remaining: 363ms
150:	learn: 4.9918472	total: 64.5ms	remaining: 363ms
151:	learn: 4.9879543	total: 65ms	remaining: 363ms
152:	learn: 4.9854869	total: 65.5ms	remaining: 362ms
153:	learn: 4.9794048	total: 65.9ms	remaining: 362ms
154:	learn: 4.9748207	total: 66.3ms	remaining: 361ms
155:	learn: 4.9741212	total: 66.5ms	remaining: 360ms
156:	learn: 4.9680668	total: 66.9ms	remaining: 359ms
157:	learn: 4.9643768	total: 67.3ms	remaining: 359ms
158:	learn: 4.9588028	total: 67.7ms	remaining: 358ms
159:	learn: 4.9561928	total: 68.1ms	remaining: 357ms
160:	learn: 4.9496095	total: 68.5ms	remaining: 357ms
161:	learn: 4.9459310	total: 68.9ms	remaining: 356ms
162:	learn: 4.9424114	total: 69.3ms	remaining: 356ms
163:	learn: 4.9381430	total: 69.7ms	remaining: 355ms
164:	learn: 4.9354872	total: 70.2ms	remaining: 355ms
165:	learn: 4.9333233	total: 70.6ms	remaining: 355ms
166:	learn: 4.9312465	total: 71ms	remaining: 354ms
167:	learn: 4.9256684	total: 71.4ms	remaining: 354ms
168:	learn: 4.9240569	total: 71.8ms	remaining: 353ms
169:	learn: 4.9209591	total: 72.2ms	remaining: 353ms
170:	learn: 4.9177489	total: 72.6ms	remaining: 352ms
171:	learn: 4.9135851	total: 73ms	remaining: 352ms
172:	learn: 4.9101853	total: 73.4ms	remaining: 351ms
173:	learn: 4.9041289	total: 73.8ms	remaining: 350ms
174:	learn: 4.8996436	total: 74.2ms	remaining: 350ms
175:	learn: 4.8968905	total: 74.6ms	remaining: 349ms
176:	learn: 4.8924892	total: 75ms	remaining: 349ms
177:	learn: 4.8893081	total: 75.6ms	remaining: 349ms
178:	learn: 4.8846526	total: 76.1ms	remaining: 349ms
179:	learn: 4.8813912	total: 76.5ms	remaining: 348ms
180:	learn: 4.8747812	total: 76.9ms	remaining: 348ms
181:	learn: 4.8681398	total: 77.3ms	remaining: 347ms
182:	learn: 4.8658891	total: 77.7ms	remaining: 347ms
183:	learn: 4.8635134	total: 78ms	remaining: 346ms
184:	learn: 4.8603607	total: 78.4ms	remaining: 346ms
185:	learn: 4.8584060	total: 78.8ms	remaining: 345ms
186:	learn: 4.8508451	total: 79.2ms	remaining: 344ms
187:	learn: 4.8474098	total: 79.6ms	remaining: 344ms
188:	learn: 4.8423499	total: 80ms	remaining: 343ms
189:	learn: 4.8383033	total: 80.4ms	remaining: 343ms
190:	learn: 4.8361532	total: 80.9ms	remaining: 343ms
191:	learn: 4.8336296	total: 81.3ms	remaining: 342ms
192:	learn: 4.8263837	total: 81.7ms	remaining: 342ms
193:	learn: 4.8228306	total: 82.1ms	remaining: 341ms
194:	learn: 4.8199848	total: 82.5ms	remaining: 341ms
195:	learn: 4.8155286	total: 82.9ms	remaining: 340ms
196:	learn: 4.8127984	total: 83.3ms	remaining: 339ms
197:	learn: 4.8080543	total: 83.7ms	remaining: 339ms
198:	learn: 4.8039138	total: 84.1ms	remaining: 338ms
199:	learn: 4.8010630	total: 84.4ms	remaining: 338ms
200:	learn: 4.7943394	total: 84.8ms	remaining: 337ms
201:	learn: 4.7915761	total: 85.2ms	remaining: 337ms
202:	learn: 4.7870146	total: 85.7ms	remaining: 337ms
203:	learn: 4.7836862	total: 86.2ms	remaining: 336ms
204:	learn: 4.7794330	total: 86.6ms	remaining: 336ms
205:	learn: 4.7766261	total: 87ms	remaining: 335ms
206:	learn: 4.7715985	total: 87.4ms	remaining: 335ms
207:	learn: 4.7680852	total: 87.8ms	remaining: 334ms
208:	learn: 4.7649356	total: 88.2ms	remaining: 334ms
209:	learn: 4.7622962	total: 88.6ms	remaining: 333ms
210:	learn: 4.7592966	total: 89ms	remaining: 333ms
211:	learn: 4.7572150	total: 89.3ms	remaining: 332ms
212:	learn: 4.7522527	total: 89.8ms	remaining: 332ms
213:	learn: 4.7512746	total: 90.1ms	remaining: 331ms
214:	learn: 4.7478228	total: 90.5ms	remaining: 331ms
215:	learn: 4.7468977	total: 91ms	remaining: 330ms
216:	learn: 4.7429584	total: 91.4ms	remaining: 330ms
217:	learn: 4.7411300	total: 91.8ms	remaining: 329ms
218:	learn: 4.7385715	total: 92.2ms	remaining: 329ms
219:	learn: 4.7340529	total: 92.6ms	remaining: 328ms
220:	learn: 4.7283270	total: 93ms	remaining: 328ms
221:	learn: 4.7231037	total: 93.4ms	remaining: 327ms
222:	learn: 4.7187074	total: 93.8ms	remaining: 327ms
223:	learn: 4.7164773	total: 94.2ms	remaining: 326ms
224:	learn: 4.7128767	total: 94.6ms	remaining: 326ms
225:	learn: 4.7092172	total: 95ms	remaining: 325ms
226:	learn: 4.7063142	total: 95.4ms	remaining: 325ms
227:	learn: 4.7034986	total: 95.8ms	remaining: 324ms
228:	learn: 4.7012607	total: 96.2ms	remaining: 324ms
229:	learn: 4.6976090	total: 96.9ms	remaining: 325ms
230:	learn: 4.6941376	total: 97.4ms	remaining: 324ms
231:	learn: 4.6930319	total: 97.8ms	remaining: 324ms
232:	learn: 4.6901410	total: 98.2ms	remaining: 323ms
233:	learn: 4.6861368	total: 98.6ms	remaining: 323ms
234:	learn: 4.6837777	total: 99ms	remaining: 322ms
235:	learn: 4.6806570	total: 99.4ms	remaining: 322ms
236:	learn: 4.6773348	total: 99.8ms	remaining: 321ms
237:	learn: 4.6764144	total: 100ms	remaining: 321ms
238:	learn: 4.6744079	total: 101ms	remaining: 320ms
239:	learn: 4.6740376	total: 101ms	remaining: 320ms
240:	learn: 4.6704480	total: 102ms	remaining: 320ms
241:	learn: 4.6680407	total: 102ms	remaining: 319ms
242:	learn: 4.6641908	total: 102ms	remaining: 319ms
243:	learn: 4.6605208	total: 103ms	remaining: 319ms
244:	learn: 4.6561600	total: 103ms	remaining: 318ms
245:	learn: 4.6557418	total: 104ms	remaining: 318ms
246:	learn: 4.6518110	total: 104ms	remaining: 317ms
247:	learn: 4.6474810	total: 105ms	remaining: 317ms
248:	learn: 4.6446722	total: 105ms	remaining: 316ms
249:	learn: 4.6390643	total: 105ms	remaining: 316ms
250:	learn: 4.6337823	total: 106ms	remaining: 316ms
251:	learn: 4.6316041	total: 106ms	remaining: 315ms
252:	learn: 4.6290638	total: 107ms	remaining: 315ms
253:	learn: 4.6248916	total: 107ms	remaining: 315ms
254:	learn: 4.6213987	total: 108ms	remaining: 314ms
255:	learn: 4.6179446	total: 108ms	remaining: 314ms
256:	learn: 4.6155745	total: 109ms	remaining: 314ms
257:	learn: 4.6145124	total: 109ms	remaining: 313ms
258:	learn: 4.6112544	total: 109ms	remaining: 313ms
259:	learn: 4.6110871	total: 110ms	remaining: 312ms
260:	learn: 4.6097521	total: 110ms	remaining: 312ms
261:	learn: 4.6068795	total: 110ms	remaining: 311ms
262:	learn: 4.6004152	total: 111ms	remaining: 311ms
263:	learn: 4.5974845	total: 111ms	remaining: 310ms
264:	learn: 4.5946783	total: 112ms	remaining: 310ms
265:	learn: 4.5932095	total: 112ms	remaining: 309ms
266:	learn: 4.5906373	total: 113ms	remaining: 309ms
267:	learn: 4.5853215	total: 113ms	remaining: 309ms
268:	learn: 4.5810524	total: 113ms	remaining: 308ms
269:	learn: 4.5789103	total: 114ms	remaining: 308ms
270:	learn: 4.5786670	total: 114ms	remaining: 307ms
271:	learn: 4.5783278	total: 115ms	remaining: 307ms
272:	learn: 4.5758070	total: 115ms	remaining: 306ms
273:	learn: 4.5754030	total: 115ms	remaining: 306ms
274:	learn: 4.5712108	total: 116ms	remaining: 306ms
275:	learn: 4.5668624	total: 116ms	remaining: 305ms
276:	learn: 4.5611512	total: 117ms	remaining: 305ms
277:	learn: 4.5609051	total: 117ms	remaining: 304ms
278:	learn: 4.5575229	total: 118ms	remaining: 304ms
279:	learn: 4.5530895	total: 118ms	remaining: 304ms
280:	learn: 4.5490170	total: 119ms	remaining: 303ms
281:	learn: 4.5464181	total: 119ms	remaining: 303ms
282:	learn: 4.5459781	total: 119ms	remaining: 302ms
283:	learn: 4.5436267	total: 120ms	remaining: 302ms
284:	learn: 4.5368667	total: 120ms	remaining: 301ms
285:	learn: 4.5304821	total: 121ms	remaining: 301ms
286:	learn: 4.5279254	total: 121ms	remaining: 300ms
287:	learn: 4.5238339	total: 121ms	remaining: 300ms
288:	learn: 4.5236395	total: 122ms	remaining: 299ms
289:	learn: 4.5234285	total: 122ms	remaining: 299ms
290:	learn: 4.5211068	total: 122ms	remaining: 298ms
291:	learn: 4.5181500	total: 123ms	remaining: 298ms
292:	learn: 4.5152698	total: 123ms	remaining: 298ms
293:	learn: 4.5130753	total: 124ms	remaining: 297ms
294:	learn: 4.5072542	total: 124ms	remaining: 297ms
295:	learn: 4.5070549	total: 125ms	remaining: 296ms
296:	learn: 4.5021725	total: 125ms	remaining: 296ms
297:	learn: 4.5006379	total: 125ms	remaining: 295ms
298:	learn: 4.4976659	total: 126ms	remaining: 295ms
299:	learn: 4.4955998	total: 126ms	remaining: 294ms
300:	learn: 4.4919470	total: 127ms	remaining: 294ms
301:	learn: 4.4917041	total: 127ms	remaining: 293ms
302:	learn: 4.4874027	total: 127ms	remaining: 293ms
303:	learn: 4.4825610	total: 128ms	remaining: 292ms
304:	learn: 4.4781698	total: 128ms	remaining: 292ms
305:	learn: 4.4751757	total: 129ms	remaining: 291ms
306:	learn: 4.4730226	total: 129ms	remaining: 291ms
307:	learn: 4.4703682	total: 129ms	remaining: 291ms
308:	learn: 4.4701971	total: 130ms	remaining: 290ms
309:	learn: 4.4689925	total: 130ms	remaining: 290ms
310:	learn: 4.4655486	total: 131ms	remaining: 289ms
311:	learn: 4.4635385	total: 131ms	remaining: 289ms
312:	learn: 4.4605155	total: 131ms	remaining: 288ms
313:	learn: 4.4572600	total: 132ms	remaining: 288ms
314:	learn: 4.4566248	total: 132ms	remaining: 287ms
315:	learn: 4.4522080	total: 133ms	remaining: 287ms
316:	learn: 4.4496875	total: 133ms	remaining: 287ms
317:	learn: 4.4495310	total: 134ms	remaining: 287ms
318:	learn: 4.4493780	total: 134ms	remaining: 287ms
319:	learn: 4.4476807	total: 135ms	remaining: 286ms
320:	learn: 4.4453737	total: 135ms	remaining: 286ms
321:	learn: 4.4452270	total: 136ms	remaining: 285ms
322:	learn: 4.4409961	total: 136ms	remaining: 285ms
323:	learn: 4.4360566	total: 136ms	remaining: 284ms
324:	learn: 4.4315087	total: 137ms	remaining: 284ms
325:	learn: 4.4286852	total: 137ms	remaining: 284ms
326:	learn: 4.4242935	total: 138ms	remaining: 283ms
327:	learn: 4.4186969	total: 138ms	remaining: 283ms
328:	learn: 4.4139708	total: 138ms	remaining: 282ms
329:	learn: 4.4094334	total: 139ms	remaining: 282ms
330:	learn: 4.4052714	total: 139ms	remaining: 281ms
331:	learn: 4.4019197	total: 140ms	remaining: 281ms
332:	learn: 4.4000805	total: 140ms	remaining: 281ms
333:	learn: 4.3976330	total: 140ms	remaining: 280ms
334:	learn: 4.3928151	total: 141ms	remaining: 280ms
335:	learn: 4.3917774	total: 141ms	remaining: 279ms
336:	learn: 4.3886566	total: 142ms	remaining: 279ms
337:	learn: 4.3837803	total: 142ms	remaining: 278ms
338:	learn: 4.3808963	total: 142ms	remaining: 278ms
339:	learn: 4.3778635	total: 143ms	remaining: 277ms
340:	learn: 4.3759558	total: 143ms	remaining: 277ms
341:	learn: 4.3743923	total: 144ms	remaining: 276ms
342:	learn: 4.3715038	total: 144ms	remaining: 276ms
343:	learn: 4.3687745	total: 144ms	remaining: 276ms
344:	learn: 4.3662128	total: 145ms	remaining: 275ms
345:	learn: 4.3641807	total: 145ms	remaining: 275ms
346:	learn: 4.3587925	total: 146ms	remaining: 274ms
347:	learn: 4.3547202	total: 146ms	remaining: 274ms
348:	learn: 4.3492792	total: 147ms	remaining: 273ms
349:	learn: 4.3445866	total: 147ms	remaining: 273ms
350:	learn: 4.3415191	total: 147ms	remaining: 272ms
351:	learn: 4.3364291	total: 148ms	remaining: 272ms
352:	learn: 4.3345971	total: 148ms	remaining: 272ms
353:	learn: 4.3304282	total: 149ms	remaining: 271ms
354:	learn: 4.3263494	total: 149ms	remaining: 271ms
355:	learn: 4.3228947	total: 149ms	remaining: 270ms
356:	learn: 4.3220642	total: 150ms	remaining: 270ms
357:	learn: 4.3209129	total: 150ms	remaining: 269ms
358:	learn: 4.3191392	total: 151ms	remaining: 269ms
359:	learn: 4.3164121	total: 151ms	remaining: 269ms
360:	learn: 4.3160390	total: 151ms	remaining: 268ms
361:	learn: 4.3143263	total: 152ms	remaining: 268ms
362:	learn: 4.3103051	total: 152ms	remaining: 267ms
363:	learn: 4.3089526	total: 153ms	remaining: 267ms
364:	learn: 4.3071779	total: 153ms	remaining: 266ms
365:	learn: 4.3034991	total: 153ms	remaining: 266ms
366:	learn: 4.3022700	total: 154ms	remaining: 265ms
367:	learn: 4.3019113	total: 154ms	remaining: 265ms
368:	learn: 4.2987829	total: 155ms	remaining: 265ms
369:	learn: 4.2976290	total: 155ms	remaining: 264ms
370:	learn: 4.2952276	total: 156ms	remaining: 264ms
371:	learn: 4.2915079	total: 156ms	remaining: 263ms
372:	learn: 4.2910186	total: 156ms	remaining: 263ms
373:	learn: 4.2871264	total: 157ms	remaining: 262ms
374:	learn: 4.2830140	total: 157ms	remaining: 262ms
375:	learn: 4.2811678	total: 158ms	remaining: 261ms
376:	learn: 4.2786374	total: 158ms	remaining: 261ms
377:	learn: 4.2735845	total: 158ms	remaining: 261ms
378:	learn: 4.2734972	total: 159ms	remaining: 260ms
379:	learn: 4.2675992	total: 159ms	remaining: 260ms
380:	learn: 4.2652312	total: 160ms	remaining: 259ms
381:	learn: 4.2635917	total: 160ms	remaining: 259ms

,Train R_Square,Train MSE,Train MAE,Test R_Square,Test MSE,Test MAE
Linear Regression,0.874317,28.334870,4.266712,0.880433,29.095170,4.214763
Ridge,0.874296,28.339635,4.265009,0.880450,29.091086,4.212527
Lasso,0.807223,43.461113,5.205262,0.825446,42.475807,5.155720
Support Vector Regressor,0.798493,45.429346,4.980786,0.713544,69.705851,5.499555
KNN,0.862290,31.046400,4.459500,0.777305,54.190200,5.703000
Decision Tree,0.999653,0.078125,0.018750,0.758361,58.800000,6.080000
Random Forest,0.977173,5.146376,1.815889,0.850300,36.427772,4.667029
Adaptive Boosting,0.852842,33.176365,4.722759,0.851553,36.122753,4.698642
Cat Boosting,0.957509,9.579513,2.444468,0.850263,36.436822,4.631211
XG Boosting,0.995101,1.104491,0.710088,0.825046,42.573135,5.078543

Linear Regression model is performing better on this dataset.